# Generated by Django 3.2.7 on 2021-11-08 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_buyer_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
