# Generated by Django 3.2.7 on 2021-11-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20211025_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='application_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category'),
        ),
    ]
