# Generated by Django 3.2.8 on 2021-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20211025_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
