# Generated by Django 3.2.7 on 2021-11-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_seller_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='application_status',
            field=models.BooleanField(),
        ),
    ]
