# Generated by Django 3.2.7 on 2021-11-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_seller_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='application_status',
            field=models.BooleanField(default=False),
        ),
    ]
