# Generated by Django 3.2.7 on 2021-11-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_product_category'),
        ('ecommerce', '0006_rename_pending_seller_applied'),
    ]

    operations = [
    ]
