# Generated by Django 3.2.7 on 2021-11-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_merge_20211107_1928'),
        ('ecommerce', '0009_auto_20211107_2011'),
    ]

    operations = [
    ]
