# Generated by Django 3.2.7 on 2021-11-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_merge_20211108_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='application_status',
            new_name='approved',
        ),
    ]
