# Generated by Django 3.2.7 on 2021-11-08 11:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_filesupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesUpload',
        ),
        migrations.AddField(
            model_name='seller',
            name='document',
            field=models.FileField(default='settings.MEDIA_ROOT/media/default_file.txt', storage=django.core.files.storage.FileSystemStorage(location='/home/shashank/Desktop/fcs/media'), upload_to='documents'),
        ),
    ]
